### ISSUE TITLE
warps get deleted when i restart server

### ISSUE THREAD

**Issue by Bidou0418** [Falkirks/WarpSigns#3]
i do setwarp xxx, make a sign and test, then i restart server and then, i get warp doesnt exist...
is it related to simple warp or warpsigns???
genisys 380 latest

**Comment by falkirks** [comment]
SimpleWarp. Neither plugin supports genisys.You are likely getting this error because the server isn't shutting down gracefully and the warps aren't being saved correctly.

**Comment by falkirks** [comment]
I am locking this because I do not support third party builds and this issue belongs in the SimpleWarp repo.
